services:
  kokoro:
    build:
      context: ./kokoro
      dockerfile: dockerfile.dockerfile
    volumes:
      - ./kokoro:/app
    command: python demo.py

  elevan:
    build:
      context: ./elevan
      dockerfile: dockerfile.dockerfile
    volumes:
      - ./elevan:/app
    command: python demo.py